daemon=false
log=stdout
loglevel=info
notransit=true
ntcp2.published=false
ssu2.published=false
i2cp.enabled=true
i2cp.address=127.0.0.1
i2cp.port=7654
sam.enabled=true
sam.address=127.0.0.1
sam.port=7656
sam.portudp=7655
sam.singlethread=true
i2pcontrol.enabled=false